#!/usr/bin/env node
// Builds the GitHub flows in flows/ from the blocks in blocks/, so they never drift apart.
// Usage: node scripts/build-flows.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse, stringify } from "yaml";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const block = (id) => parse(readFileSync(join(root, "blocks", `${id}.yaml`), "utf8")).steps;
const steps = (...ids) => ids.flatMap((id) => (typeof id === "string" ? block(id) : [id]));
const patch = (list, id, fields) => Object.assign(list.find((s) => s.id === id), fields);

function write(name, header, flow) {
  const text = `# ${"─".repeat(3)} ${header.title} ${"─".repeat(Math.max(3, 66 - header.title.length))}
# Generated by scripts/build-flows.mjs from blocks/*.yaml — edit the blocks or the script.
${header.lines.map((l) => `# ${l}`).join("\n")}
# ${"─".repeat(72)}
`;
  // Flows that change code: one run per repository at a time. Planning / PR-only flows run in parallel.
  const { description, workspace, ...rest } = flow;
  const coding = !["issue-plan", "daily-pr"].includes(name);
  const ordered = { name, description, workspace, ...(coding ? { one_per_repo: true } : {}), ...rest };
  writeFileSync(join(root, "flows", `${name}.yaml`), text + stringify(ordered, { lineWidth: 0 }));
  console.log(`wrote flows/${name}.yaml (${flow.steps.length} steps)`);
}

const ticketStart = () => {
  const s = steps("github-repo", "pull-ticket", "pull-repo", "plan", "push-plan", "code", "run-tests", "code-review");
  // After someone answers the questions, re-read the ticket and plan again.
  patch(s, "ask_for_info", { resume_from: "pull_ticket" });
  // After review changes, re-run the tests before reviewing again.
  patch(s, "address_review", { on_success: "run_tests" });
  return s;
};

// ── github-issue: ticket → pushed branch ──
write("github-issue", {
  title: "GitHub ticket → code → pushed branch",
  lines: [
    "factory run github-issue --var github_repo=owner/repo --var issue=42",
    "",
    "check repo → pull ticket → clone → plan ─┬─ unclear → ask on ticket → stop (resumes when answered)",
    "                                         └─ ready → post plan → code",
    "  → tests ⟲ fix → review ⟲ address (→ tests) → commit → push → report on ticket",
  ],
}, {
  description: "GitHub ticket → plan (or ask for info) → code → tests → review → commit, push, report",
  workspace: "empty",
  defaults: { model: "claude-sonnet-5-5", timeout_sec: 1800 },
  limits: { max_cost_usd: 15 },
  vars: { github_repo: "owner/repo", issue: "", test_cmd: "auto" },
  steps: [...ticketStart(), ...steps("commit", "push", "push-result")],
});

// ── github-pr: ticket → PR → green CI ──
{
  const s = [
    ...ticketStart(),
    ...steps("commit"),
    {
      id: "approval_gate",
      type: "shell",
      description: "Set var require_approval=yes to ask on the ticket before pushing",
      run: 'echo "APPROVAL: ${FACTORY_VAR_REQUIRE_APPROVAL:-no}"',
      routes: [{ if: "^APPROVAL: yes", goto: "request_approval" }],
    },
    ...steps("request-approval", "push", "open-pr", "ci", "push-result", "learn"),
  ];
  patch(s, "request_approval", { jump_only: true, on_success: "approve" });
  patch(s, "approve", { jump_only: true, on_success: "push" });
  write("github-pr", {
    title: "GitHub ticket → pull request → green CI",
    lines: [
      "factory run github-pr --var github_repo=owner/repo --var issue=42 [--var require_approval=yes]",
      "",
      "like github-issue, then: [approval on ticket] → push → open PR → wait for CI ⟲ fix → report → learn",
    ],
  }, {
    description: "GitHub ticket → plan → code → tests → review → PR → CI fix loop → report → learn",
    workspace: "empty",
    defaults: { model: "claude-sonnet-5-5", timeout_sec: 1800 },
    limits: { max_cost_usd: 20 },
    vars: { github_repo: "owner/repo", issue: "", test_cmd: "auto", require_approval: "no" },
    steps: s,
  });
}

// ── github-auto: triage decides small / feature / split / questions ──
{
  const s = [
    ...steps("github-repo", "pull-ticket", "pull-repo", "triage", "plan", "push-plan", "code", "run-tests", "code-review", "commit", "push", "open-pr", "ci", "push-result", "learn"),
  ];
  patch(s, "triage", {
    routes: [
      { if: "^ROUTE: NEEDS_INFO", goto: "ask_for_info" },
      { if: "^ROUTE: SPLIT", goto: "split_ticket" },
      { if: "^ROUTE: SMALL", goto: "implement" },
    ],
  });
  patch(s, "ask_for_info", { resume_from: "pull_ticket" });
  patch(s, "address_review", { on_success: "run_tests" });
  write("github-auto", {
    title: "GitHub ticket → triage → the right amount of process",
    lines: [
      "factory run github-auto --var github_repo=owner/repo --var issue=42",
      "",
      "triage ─┬─ SMALL      → code → tests → review → PR → CI",
      "        ├─ FEATURE    → plan → post plan → code → …",
      "        ├─ SPLIT      → create sub-issues (labelled claude-factory if auto_subtasks=yes) → end",
      "        └─ NEEDS_INFO → ask on the ticket → stop (resumes when answered)",
    ],
  }, {
    description: "Triage the ticket, then small fix, full feature, split into sub-issues, or ask questions",
    workspace: "empty",
    defaults: { model: "claude-sonnet-5-5", timeout_sec: 1800 },
    limits: { max_cost_usd: 20 },
    vars: { github_repo: "owner/repo", issue: "", test_cmd: "auto", auto_subtasks: "no" },
    steps: s,
  });
}

// ── jira-ticket / linear-ticket: tickets elsewhere, code in the local repo ──
for (const [tool, label] of [["jira", "Jira"], ["linear", "Linear"]]) {
  const s = [
    ...steps(`${tool}-pull-ticket`, "plan"),
    ...steps(`${tool}-push-plan`, "code", "run-tests", "code-review", "commit"),
    { id: "push", type: "shell", run: 'git push -q -u origin HEAD && echo "pushed $(git branch --show-current)"' },
    ...steps(`${tool}-push-result`),
  ];
  // Without GitHub there is nowhere to ask; stop so a human can look at the questions in the run.
  patch(s, "ask_for_info", {
    run: 'printf \'%s\n\' "$FACTORY_OUT_PLAN" | sed -E \'/^(PLAN_STATUS|ROUTE):/d\'',
    on_success: "stop",
    resume_from: "pull_ticket",
    description: "Show Claude's questions and stop; answer on the ticket, then resume the run",
  });
  patch(s, "address_review", { on_success: "run_tests" });
  write(`${tool}-ticket`, {
    title: `${label} ticket → code in this repo → pushed branch`,
    lines: [
      `factory run ${tool}-ticket --var ticket=${tool === "jira" ? "PROJ-123" : "ENG-123"}   (from inside your repo)`,
      tool === "jira" ? "needs env JIRA_BASE_URL, JIRA_EMAIL, JIRA_API_TOKEN" : "needs env LINEAR_API_KEY",
    ],
  }, {
    description: `${label} ticket → plan (posted to ${label}) → code → tests → review → commit → push → result on ${label}`,
    workspace: "worktree",
    defaults: { model: "claude-sonnet-5-5", timeout_sec: 1800 },
    limits: { max_cost_usd: 15 },
    vars: { ticket: "", test_cmd: "auto" },
    steps: s,
  });
}

// ── pr-feedback: address review comments on a factory PR ──
write("pr-feedback", {
  title: "Address review comments on a pull request",
  lines: ["factory run pr-feedback --var github_repo=owner/repo --var pr=17", "(the watcher runs this automatically for new comments on factory PRs)"],
}, {
  description: "Check out a PR, address its review comments, test, push, reply on the PR",
  workspace: "empty",
  defaults: { model: "claude-sonnet-5-5", timeout_sec: 1800 },
  limits: { max_cost_usd: 10 },
  vars: { github_repo: "owner/repo", pr: "", test_cmd: "auto" },
  steps: [
    ...steps("pr-comments", "run-tests"),
    {
      id: "push_changes",
      type: "shell",
      run: [
        "git add -A",
        'git diff --cached --quiet && { echo "no code changes"; exit 0; }',
        'git commit -q -m "Address review comments" -m "Automated by claude-factory (run $FACTORY_RUN_ID)"',
        "git push -q && git log --oneline -1",
      ].join("\n"),
    },
    {
      id: "reply",
      type: "shell",
      run: [
        '{ echo "🤖 **claude-factory** went through the review comments:"; echo',
        '  printf \'%s\\n\' "$FACTORY_OUT_ADDRESS_COMMENTS"',
        '  echo; echo "<!-- claude-factory run=$FACTORY_RUN_ID -->"; } \\',
        '  | gh pr comment "$FACTORY_VAR_PR" --repo "$FACTORY_VAR_GITHUB_REPO" --body-file -',
      ].join("\n"),
    },
  ],
});

// ── ci-fix: CI failing on the default branch → fix PR ──
{
  const s = [
    ...steps("github-repo", "pull-repo"),
    {
      id: "ci_logs",
      type: "shell",
      description: "Failed job logs of CI run ci_run (set by the ci-failures watcher)",
      run: [
        'case "$FACTORY_VAR_CI_RUN" in *[!0-9]*|"") echo "set var ci_run to a GitHub Actions run id"; exit 1;; esac',
        'gh run view "$FACTORY_VAR_CI_RUN" --repo "$FACTORY_VAR_GITHUB_REPO" --json workflowName,headSha,headBranch,url \\',
        '  --jq \'"workflow: \\(.workflowName)\\ncommit: \\(.headSha)\\nbranch: \\(.headBranch)\\nurl: \\(.url)"\'',
        'echo; echo "=== failed job logs (tail) ==="',
        'gh run view "$FACTORY_VAR_CI_RUN" --repo "$FACTORY_VAR_GITHUB_REPO" --log-failed 2>&1 | tail -200',
      ].join("\n"),
    },
    {
      id: "implement",
      type: "claude",
      permission_mode: "acceptEdits",
      allowed_tools: ["Read", "Edit", "Write", "Glob", "Grep", "Bash(npm *)", "Bash(npx *)", "Bash(git log*)", "Bash(git diff*)", "Bash(git show*)"],
      prompt: [
        "CI is failing on the default branch. Find the root cause and fix it with the smallest",
        "correct change. Do not disable, skip or loosen tests or checks. Use `git log` to see which",
        "recent commits could have caused it.",
        "",
        "{{steps.ci_logs.output}}",
        "",
        "Things learned from earlier runs in this repo:",
        "{{learnings}}",
        "",
        "Finish with a short summary of the cause and the fix.",
      ].join("\n"),
    },
    ...steps("run-tests", "code-review", "commit", "push", "open-pr", "ci", "learn"),
  ];
  patch(s, "address_review", { on_success: "run_tests" });
  write("ci-fix", {
    title: "CI failing on the default branch → fix pull request",
    lines: [
      "factory run ci-fix --var github_repo=owner/repo --var ci_run=123456789",
      "(the ci-failures watcher runs this when the latest run of a workflow on the default branch failed)",
      "",
      "clone → failed logs → fix → tests ⟲ fix → review ⟲ address → commit → push → PR → CI ⟲ fix → learn",
    ],
  }, {
    description: "Fix CI that is red on the default branch: read the failed logs, fix, test, review, open a PR",
    workspace: "empty",
    defaults: { model: "claude-sonnet-5-5", timeout_sec: 1800 },
    limits: { max_cost_usd: 15 },
    vars: { github_repo: "owner/repo", ci_run: "", test_cmd: "auto" },
    steps: s,
  });
}

// ── chore: recurring maintenance on a schedule → PR (or nothing) ──
{
  const s = [
    ...steps("github-repo", "pull-repo"),
    {
      id: "implement",
      type: "claude",
      permission_mode: "acceptEdits",
      allowed_tools: ["Read", "Edit", "Write", "Glob", "Grep", "Bash(npm *)", "Bash(npx *)", "Bash(pnpm *)", "Bash(yarn *)", "Bash(git log*)", "Bash(git diff*)"],
      prompt: [
        "Recurring maintenance task for this repository:",
        "",
        "{{task}}",
        "",
        "Keep the change focused and safe to merge. If nothing needs to be done, change nothing",
        "and answer with exactly: NOTHING_TO_DO",
        "Otherwise finish with a short summary of what you changed and why.",
      ].join("\n"),
      routes: [{ if: "^NOTHING_TO_DO\\s*$", goto: "end" }],
    },
    ...steps("run-tests", "code-review", "commit", "push", "open-pr", "ci"),
  ];
  patch(s, "address_review", { on_success: "run_tests" });
  write("chore", {
    title: "Scheduled chore → pull request (or nothing to do)",
    lines: [
      'factory run chore --var github_repo=owner/repo "Update dependencies with known vulnerabilities"',
      "(a schedule watcher runs this on a timer with its task)",
      "",
      "clone → do the chore ─┬─ nothing to do → end",
      "                      └─ changed → tests ⟲ fix → review → commit → push → PR → CI ⟲ fix",
    ],
  }, {
    description: "Recurring maintenance (deps, flaky tests, docs…) on a schedule; opens a PR only if something changed",
    workspace: "empty",
    defaults: { model: "claude-sonnet-5-5", timeout_sec: 1800 },
    limits: { max_cost_usd: 10 },
    vars: { github_repo: "owner/repo", test_cmd: "auto" },
    steps: s,
  });
}

// ── Label-driven pipeline: issue-plan → issue-code-daily → daily-pr ──
// Watchers move issues through labels (e.g. Factory_ready → Factory_planned → Factory_code → Factory_done).
const clone = {
  id: "clone",
  type: "shell",
  run: 'if [ -d .git ]; then git fetch -q origin; else gh repo clone "$FACTORY_VAR_GITHUB_REPO" . -- -q; fi\ngit log --oneline -1',
};

// The plan text: the revised plan when there is one, else the first draft.
const PLAN_OUT = '"${FACTORY_OUT_REVISE_PLAN:-$FACTORY_OUT_PLAN}"';

write("issue-plan", {
  title: "Plan a GitHub issue and post the plan (label-driven)",
  lines: [
    "factory run issue-plan --var github_repo=owner/repo --var issue=42",
    "(a watcher on the plan label runs this; when it succeeds the watcher swaps the labels)",
    "",
    "pull ticket → clone → plan (Opus 5.5, xhigh effort, read-only)",
    "  ─┬─ READY → Codex checks the plan against the code ─┬─ approved → post plan → done",
    "   │                                                  └─ issues → Opus revises → post plan → done",
    "   └─ NEEDS_INFO / NOT_CODE / TOO_BIG → post why → stop (resumes and re-plans when you reply)",
  ],
}, {
  description: "Plan an issue with Opus (xhigh effort), have Codex check it against the code, revise, post; send back unclear/non-code/too-big issues",
  workspace: "empty",
  defaults: { timeout_sec: 2400 },
  limits: { max_cost_usd: 8 },
  vars: { github_repo: "owner/repo", issue: "", code_label: "Factory_code", ready_label: "Factory_ready", forbidden_paths: "" },
  steps: [
    ...steps("pull-ticket"),
    clone,
    {
      id: "plan",
      type: "claude",
      model: "claude-opus-5-5",
      effort: "xhigh",
      permission_mode: "dontAsk",
      allowed_tools: ["Read", "Glob", "Grep", "Bash(git log*)", "Bash(git show*)", "Bash(git grep*)", "Bash(ls*)"],
      prompt: [
        "You are the lead architect for this repository. Plan the work for the GitHub issue below so that",
        "another engineer can implement it without having to make design decisions. Do NOT modify files.",
        "",
        "{{steps.pull_ticket.output}}",
        "",
        "Paths that must not be changed: {{vars.forbidden_paths}}",
        "Earlier comments may contain a previous plan and feedback on it — the feedback wins.",
        "",
        "Investigate before you write (this is the most important part):",
        "- Read CLAUDE.md, the design docs it points to, and the parts of the code this issue touches.",
        "- Find the existing classes, interfaces and patterns to reuse or extend, and how similar features",
        "  were built. Check how the code is tested today (test style, helpers, fixtures).",
        "- Verify every class, file, function and module you mention actually exists as you describe it.",
        "  If something must be created, say so explicitly.",
        "",
        "Then decide:",
        "- NOT_CODE: not a coding task (legal, approval, research, rollout, …). Explain why.",
        "- TOO_BIG: cannot be done well as one focused, reviewable change. Propose a split into smaller",
        "  issues (title + 2-3 lines each) that can each be built and tested on their own, in order.",
        "- NEEDS_INFO: a decision only the owner can make, or missing requirements. Ask specific questions",
        "  with the options you see and your recommendation. Do not guess on things that matter.",
        "- READY: write the plan with these sections:",
        "  ## Goal — what will work when this is done, in one or two sentences.",
        "  ## Acceptance criteria — a checklist that can be verified.",
        "  ## Design — the approach, and why it fits the existing architecture. Alternatives you rejected, briefly.",
        "  ## Changes — per module/file (existing paths, or marked NEW): what changes. Include signatures of",
        "     new public types/functions.",
        "  ## Implementation steps — ordered, each small enough to compile and test.",
        "  ## Tests — the concrete test cases to add (unit/integration), including edge cases and failure paths.",
        "  ## Documentation — what goes in the changelog / user guide.",
        "  ## Risks & open points — what could go wrong, migrations, performance, security, compatibility.",
        "  No new dependencies unless the issue asks for them. Be concrete; skip filler.",
        "",
        "End with exactly one line: PLAN_STATUS: READY | NEEDS_INFO | NOT_CODE | TOO_BIG",
      ].join("\n"),
      routes: [{ if: "^PLAN_STATUS: READY\\s*$", goto: "plan_review" }],
      on_success: "send_back",
    },
    {
      id: "plan_review",
      type: "claude",
      agent: "codex",
      effort: "high",
      jump_only: true,
      permission_mode: "dontAsk",
      allowed_tools: ["Read", "Glob", "Grep"],
      description: "A second model checks the plan against the real code (skipped if Codex is unavailable)",
      prompt: [
        "Review this implementation plan for the GitHub issue below, against the actual code in this",
        "repository. Do not change files. Check:",
        "- Does every file, class, function and module it mentions exist as described? Wrong assumptions?",
        "- Does it cover the whole issue and all acceptance criteria? Missing steps, migrations, wiring?",
        "- Does it fit the existing architecture and patterns, or is there a simpler way that fits better?",
        "- Are the tests enough (edge cases, failure paths)? Security, data loss, concurrency risks?",
        "Report only real problems, each with what is wrong and what the plan should say instead.",
        "",
        "{{steps.pull_ticket.output}}",
        "",
        "=== PLAN ===",
        "{{steps.plan.output}}",
        "",
        "End with exactly one line: VERDICT: APPROVE   or   VERDICT: CHANGES",
      ].join("\n"),
      routes: [{ if: "^VERDICT: APPROVE\\s*$", goto: "post_plan" }],
      on_success: "revise_plan",
      on_failure: "post_plan",
    },
    {
      id: "revise_plan",
      type: "claude",
      model: "claude-opus-5-5",
      effort: "xhigh",
      resume: "plan",
      jump_only: true,
      permission_mode: "dontAsk",
      allowed_tools: ["Read", "Glob", "Grep", "Bash(git log*)", "Bash(git show*)", "Bash(git grep*)", "Bash(ls*)"],
      prompt: [
        "Another reviewer checked your plan against the code. Verify each point in the code; adopt the ones",
        "that are right and ignore the ones that are wrong. Then output the complete final plan (all",
        "sections, not just the changes), followed by a short \"## Review notes\" section listing which",
        "points you adopted and which you rejected, with one line why.",
        "",
        "{{steps.plan_review.output}}",
        "",
        "End with exactly one line: PLAN_STATUS: READY | NEEDS_INFO | NOT_CODE | TOO_BIG",
      ].join("\n"),
      routes: [{ if: "^PLAN_STATUS: READY\\s*$", goto: "post_plan" }],
      on_success: "send_back",
    },
    {
      id: "send_back",
      type: "shell",
      jump_only: true,
      description: "Post why the issue can't be planned yet, then stop (resumes when someone replies)",
      resume_from: "pull_ticket",
      run: [
        `out=${PLAN_OUT}`,
        'status=$(printf \'%s\\n\' "$out" | sed -n \'s/^PLAN_STATUS: *\\([A-Z_]*\\).*/\\1/p\' | tail -1)',
        'case "$status" in',
        '  NEEDS_INFO) head="needs more information before it can plan this issue:" ;;',
        '  NOT_CODE) head="thinks this issue is not a coding task:" ;;',
        '  TOO_BIG) head="thinks this issue is too big for one change and proposes splitting it:" ;;',
        '  *) echo "planning failed: no PLAN_STATUS line"; exit 1 ;;',
        "esac",
        '{ echo "🤖 **claude-factory** $head"; echo',
        '  printf \'%s\\n\' "$out" | sed \'/^PLAN_STATUS:/d\'',
        '  echo; echo "_Reply on this issue and it plans again._"',
        '  echo; echo "<!-- claude-factory run=$FACTORY_RUN_ID -->"; } \\',
        '  | gh issue comment "$FACTORY_VAR_ISSUE" --repo "$FACTORY_VAR_GITHUB_REPO" --body-file -',
      ].join("\n"),
      on_success: "stop",
    },
    {
      id: "post_plan",
      type: "shell",
      jump_only: true,
      run: [
        `out=${PLAN_OUT}`,
        'reviewed=""; [ -n "$FACTORY_OUT_PLAN_REVIEW" ] && reviewed=" (checked against the code by Codex)"',
        '{ echo "🤖 **claude-factory plan**$reviewed"; echo',
        '  printf \'%s\\n\' "$out" | sed \'/^PLAN_STATUS:/d\'',
        '  echo; echo "_Add the \\`$FACTORY_VAR_CODE_LABEL\\` label to start coding. To change the plan, comment what to change,"',
        '  echo "remove the planned label and add \\`$FACTORY_VAR_READY_LABEL\\` again._"',
        '  echo; echo "<!-- claude-factory run=$FACTORY_RUN_ID plan -->"; } \\',
        '  | gh issue comment "$FACTORY_VAR_ISSUE" --repo "$FACTORY_VAR_GITHUB_REPO" --body-file -',
      ].join("\n"),
      on_success: "end",
    },
  ],
});

{
  const testsRun = [
    'git add -A -N >/dev/null 2>&1 || true   # new files show up in git diff for reviewers',
    'cmd="$FACTORY_VAR_TEST_CMD"',
    'if [ -z "$cmd" ] || [ "$cmd" = auto ]; then cmd=$("$FACTORY_TOOLS/detect-commands" test); fi',
    'if [ -z "$cmd" ]; then echo "no test command found (set var test_cmd)"; exit 1; fi',
    'marker="{{run.dir}}/tests.marker"; touch "$marker"',
    'echo "\\$ $cmd"',
    'sh -c "$cmd" > "{{run.dir}}/tests.log" 2>&1; code=$?',
    'tail -150 "{{run.dir}}/tests.log"',
    'echo; echo "=== summary ==="',
    '{ "$FACTORY_TOOLS/test-summary" "$marker"; [ "$code" -eq 0 ] && echo "result: PASSED" || echo "result: FAILED (exit $code)"; } | tee "{{run.dir}}/last-tests.txt"',
    'exit "$code"',
  ].join("\n");
  const tests = (id, fixId, next) => [
    { id, type: "shell", timeout_sec: 3600, run: testsRun, on_failure: fixId, ...(next ? { on_success: next } : {}) },
    {
      id: fixId,
      type: "claude",
      // Continue the coding session: it already knows the code, no re-reading.
      resume: "implement",
      jump_only: true,
      max_visits: 3,
      prompt: [
        "The tests fail. Fix the code so they pass. Never delete, disable or weaken tests to make them pass;",
        "change a test only if the test itself is wrong, and say so.",
        "",
        `{{steps.${id}.output}}`,
      ].join("\n"),
      on_success: id,
    },
  ];
  const review = (n, skipTo) => [
    {
      id: `review_${n}`,
      type: "claude",
      agent: "codex",
      permission_mode: "dontAsk",
      allowed_tools: ["Read", "Glob", "Grep"],
      prompt: [
        `Code review, round ${n} of 2. Another AI implemented the GitHub issue below; its changes are`,
        "uncommitted in this repository (run `git status` and `git diff HEAD`). Review them strictly for",
        "correctness, edge cases, security, error handling, test coverage and fit with the existing code.",
        "Report only real problems, each with file, line, problem and the fix. No style nitpicks.",
        "",
        "{{steps.pull_ticket.output}}",
        "",
        "End with exactly one line: VERDICT: APPROVE   or   VERDICT: CHANGES",
      ].join("\n"),
      routes: [{ if: "^VERDICT: APPROVE\\s*$", goto: skipTo }],
    },
    {
      id: `address_review_${n}`,
      type: "claude",
      resume: "implement",
      prompt: [
        "A reviewer (Codex) looked at your changes. Fix every point you agree with. For points you",
        "disagree with, explain why in one line each. Keep tests passing; don't write docs yet.",
        "",
        `{{steps.review_${n}.output}}`,
      ].join("\n"),
    },
  ];

  // Checks after coding (and, with checkDocs, after the docs step).
  const guardRun = (checkDocs) => [
        "git add -A -N >/dev/null 2>&1 || true",
        "changed=$(git diff HEAD --name-only)",
        '[ -n "$changed" ] || { echo "no changes were made"; exit 1; }',
        "bad=0",
        "for p in $FACTORY_VAR_FORBIDDEN_PATHS; do",
        '  hits=$(printf \'%s\\n\' "$changed" | grep "^$p" || true)',
        '  [ -n "$hits" ] && { echo "changes in forbidden path $p:"; printf \'%s\\n\' "$hits"; bad=1; }',
        "done",
        "added=$(git diff HEAD -U0 | grep '^+' | grep -v '^+++' || true)",
        "removed=$(git diff HEAD -U0 | grep '^-' | grep -v '^---' || true)",
        "skips=$(printf '%s\\n' \"$added\" | grep -E '@Disabled|@Ignore\\b|\\.skip\\(|\\bxit\\(|\\bxdescribe\\(|@pytest\\.mark\\.skip|t\\.Skip\\(' || true)",
        '[ -n "$skips" ] && { echo "tests were disabled or skipped:"; printf \'%s\\n\' "$skips"; bad=1; }',
        "pat='@Test\\b|@ParameterizedTest|\\bit\\(|\\btest\\(|def test_'",
        "rt=$(printf '%s\\n' \"$removed\" | grep -Ec \"$pat\" || true); at=$(printf '%s\\n' \"$added\" | grep -Ec \"$pat\" || true)",
        '[ "$rt" -gt "$at" ] && { echo "tests were removed ($rt removed, $at added)"; bad=1; }',
        ...(checkDocs ? [
          "for f in $FACTORY_VAR_DOCS_REQUIRED; do",
          '  printf \'%s\\n\' "$changed" | grep -qx "$f" || { echo "documentation not updated: $f"; bad=1; }',
          "done",
        ] : []),
        '[ "$bad" = 0 ] && echo "guard ok: $(printf \'%s\\n\' "$changed" | wc -l | tr -d " ") files changed"',
        'exit "$bad"',
      ].join("\n");

  const s = [
    ...steps("pull-ticket"),
    {
      id: "daily_branch",
      type: "shell",
      description: "Clone, then check out today's branch — or wait while the daily PR is unmerged",
      // On a resume or retry, throw away half-done work from the failed attempt first.
      run: 'if [ -d .git ]; then git reset -q --hard && git clean -qfd && git fetch -q origin; else gh repo clone "$FACTORY_VAR_GITHUB_REPO" . -- -q; fi\n"$FACTORY_TOOLS/daily-branch" prepare',
      routes: [{ if: "^WAIT:", goto: "wait_for_merge" }],
    },
    { ...tests("baseline_tests", "baseline_failed")[0], description: "Tests must pass before we change anything", on_failure: "baseline_failed" },
    {
      id: "implement",
      type: "claude",
      prompt: [
        "Implement GitHub issue below in this repository.",
        "",
        "{{steps.pull_ticket.output}}",
        "",
        "Follow the plan in the latest \"claude-factory plan\" comment, including any later comments from",
        "people, which override it. Follow the repository's CLAUDE.md conventions.",
        "- Add or update tests for everything you change.",
        "- Do not add new dependencies. Do not change: {{vars.forbidden_paths}}",
        "- Do not write documentation yet; that is a separate step.",
        "- Do not commit.",
        "",
        "Things learned from earlier runs in this repo:",
        "{{learnings}}",
        "",
        "Finish with a short summary of what you changed (files and why).",
      ].join("\n"),
    },
    {
      id: "guard",
      type: "shell",
      description: "No forbidden paths, no disabled or deleted tests, something changed",
      run: guardRun(false),
      on_failure: "fix_guard",
    },
    {
      id: "fix_guard",
      type: "claude",
      resume: "implement",
      jump_only: true,
      max_visits: 2,
      prompt: "Your changes broke a rule of this factory. Fix that (restore removed/disabled tests, revert changes in forbidden paths, or make the missing change):\n\n{{steps.guard.output}}",
      on_success: "guard",
    },
    ...tests("run_tests", "fix_tests"),
    ...review(1, "docs"),
    ...tests("run_tests_1", "fix_tests_1"),
    ...review(2, "docs"),
    ...tests("run_tests_2", "fix_tests_2"),
    {
      id: "docs",
      type: "claude",
      resume: "implement",
      prompt: [
        "Now document the change you made for this issue, following the repository's documentation rules",
        "(CLAUDE.md). If there are none: update README/docs where behaviour changed, and add doc comments",
        "to new public APIs. Required files that must be updated: {{vars.docs_required}}",
        "",
        "{{steps.pull_ticket.output}}",
        "",
        "What was implemented:",
        "{{steps.implement.output}}",
      ].join("\n"),
    },
    {
      id: "final_guard",
      type: "shell",
      description: "Same checks as guard, plus: required docs were updated",
      run: guardRun(true),
      on_failure: "docs",
    },
    {
      id: "commit",
      type: "shell",
      run: [
        "git add -A",
        'title=$(gh issue view "$FACTORY_VAR_ISSUE" --repo "$FACTORY_VAR_GITHUB_REPO" --json title -q .title 2>/dev/null)',
        'git commit -q -m "Resolve #$FACTORY_VAR_ISSUE: $title" -m "Written by Claude, reviewed by Codex, tests passing. claude-factory run $FACTORY_RUN_ID"',
        "git log --oneline -1",
      ].join("\n"),
    },
    {
      id: "push",
      type: "shell",
      run: [
        "branch=$(git branch --show-current)",
        'if git ls-remote --exit-code --heads origin "$branch" >/dev/null 2>&1; then git pull -q --rebase origin "$branch"; fi',
        'git push -q -u origin HEAD && echo "pushed $branch"',
      ].join("\n"),
    },
    {
      id: "report",
      type: "shell",
      run: [
        "branch=$(git branch --show-current); sha=$(git rev-parse HEAD)",
        'verdict() { printf \'%s\\n\' "$1" | sed -n \'s/^VERDICT: *//p\' | tail -1; }',
        '{ echo "🤖 **claude-factory** implemented this on branch \\`$branch\\` (commit https://github.com/$FACTORY_VAR_GITHUB_REPO/commit/$sha)."',
        '  echo; echo "### What was done"; printf \'%s\\n\' "$FACTORY_OUT_IMPLEMENT"',
        '  echo; echo "### Review (Codex)"',
        '  echo "- round 1: $(verdict "$FACTORY_OUT_REVIEW_1")"',
        '  [ -n "$FACTORY_OUT_REVIEW_2" ] && echo "- round 2: $(verdict "$FACTORY_OUT_REVIEW_2")"',
        '  echo; echo "### Tests"; echo \'```\'; cat "{{run.dir}}/last-tests.txt"; echo \'```\'',
        '  echo; echo "### Files changed"; echo \'```\'; git show --stat --format= HEAD | tail -40; echo \'```\'',
        '  echo; echo "_This goes to main with the daily pull request._"',
        '  echo; echo "<!-- claude-factory run=$FACTORY_RUN_ID -->"; } \\',
        '  | gh issue comment "$FACTORY_VAR_ISSUE" --repo "$FACTORY_VAR_GITHUB_REPO" --body-file -',
      ].join("\n"),
      on_success: "end",
    },
    {
      id: "baseline_failed",
      type: "shell",
      jump_only: true,
      run: 'echo "The tests already fail on $(git branch --show-current) before any change — not starting."; tail -40 "{{run.dir}}/tests.log"; exit 1',
    },
    {
      id: "wait_for_merge",
      type: "shell",
      jump_only: true,
      description: "Stop until the daily PR is merged; the watcher resumes the run then",
      resume_from: "daily_branch",
      run: 'printf \'%s\\n\' "$FACTORY_OUT_DAILY_BRANCH" | grep "^WAIT:"',
      on_success: "stop",
    },
  ];
  s.find((x) => x.id === "docs").max_visits = 2;
  s.find((x) => x.id === "docs").prompt += "\n\n{{steps.final_guard.output}}";
  write("issue-code-daily", {
    title: "Code a planned issue on today's branch (label-driven)",
    lines: [
      "factory run issue-code-daily --var github_repo=owner/repo --var issue=42 --var test_cmd=\"./gradlew test\"",
      "",
      "pull ticket → today's branch (waits while the daily PR is unmerged) → baseline tests",
      "  → Claude codes → guard → tests ⟲ fix (max 3)",
      "  → Codex review 1 → Claude fixes → tests ⟲ fix (max 3)",
      "  → Codex review 2 → Claude fixes → tests ⟲ fix (max 3)      (an APPROVE skips ahead)",
      "  → docs → guard (+ docs updated) → commit \"Resolve #N\" → push → report on the issue",
    ],
  }, {
    description: "Code a planned issue on the day's branch: tests, 2 Codex reviews, docs, commit, push, report",
    workspace: "empty",
    // Cap each agent step (Claude Code stops the step when it reaches it) so one step can't run away.
    defaults: { model: "claude-sonnet-5-5", timeout_sec: 2400, max_budget_usd: 6 },
    limits: { max_cost_usd: 30 },
    vars: {
      github_repo: "owner/repo", issue: "", test_cmd: "auto", branch_prefix: "factory/daily-", timezone: "Europe/Berlin",
      forbidden_paths: "", docs_required: "",
    },
    steps: s,
  });
}

write("daily-pr", {
  title: "Open the daily pull request to main",
  lines: [
    "factory run daily-pr --var github_repo=owner/repo --var test_cmd=\"./gradlew test\"",
    "(a schedule watcher runs this at a set time, e.g. 17:00 Europe/Berlin)",
    "",
    "clone → daily branch with commits and no PR? ─┬─ none → end",
    "                                              └─ full tests + build → open PR (draft if red)",
  ],
}, {
  description: "Open the day's PR to main after running the full tests and build (draft if they fail)",
  workspace: "empty",
  defaults: { timeout_sec: 3600 },
  vars: { github_repo: "owner/repo", test_cmd: "auto", build_cmd: "", branch_prefix: "factory/daily-", timezone: "Europe/Berlin" },
  steps: [
    clone,
    {
      id: "find_branch",
      type: "shell",
      run: '"$FACTORY_TOOLS/daily-branch" pending | head -1',
      routes: [{ if: "^NONE$", goto: "end" }],
    },
    {
      id: "verify",
      type: "shell",
      description: "Full tests and build on the branch; the result goes into the PR",
      run: [
        'branch=$(printf \'%s\\n\' "$FACTORY_OUT_FIND_BRANCH" | head -1)',
        'git checkout -q -B "$branch" "origin/$branch"',
        'cmd="$FACTORY_VAR_TEST_CMD"; if [ -z "$cmd" ] || [ "$cmd" = auto ]; then cmd=$("$FACTORY_TOOLS/detect-commands" test); fi',
        'marker="{{run.dir}}/tests.marker"; touch "$marker"; ok=yes',
        'sh -c "$cmd" > "{{run.dir}}/tests.log" 2>&1 || ok=no',
        'if [ -n "$FACTORY_VAR_BUILD_CMD" ]; then sh -c "$FACTORY_VAR_BUILD_CMD" > "{{run.dir}}/build.log" 2>&1 || ok=no; fi',
        '{ echo "### Checks on this branch"; echo \'```\'; echo "\\$ $cmd"; "$FACTORY_TOOLS/test-summary" "$marker"',
        '  [ -n "$FACTORY_VAR_BUILD_CMD" ] && echo "\\$ $FACTORY_VAR_BUILD_CMD → $(grep -q "BUILD SUCCESSFUL" "{{run.dir}}/build.log" 2>/dev/null && echo ok || tail -1 "{{run.dir}}/build.log")"',
        '  echo \'```\'; [ "$ok" = yes ] || echo "⚠ **Checks failed** — opened as a draft. See the run log for details."; } > "{{run.dir}}/checks.md"',
        'cat "{{run.dir}}/checks.md"; echo "CHECKS: $ok"',
      ].join("\n"),
    },
    {
      id: "open_pr",
      type: "shell",
      run: [
        'branch=$(printf \'%s\\n\' "$FACTORY_OUT_FIND_BRANCH" | head -1)',
        'draft=""; printf \'%s\\n\' "$FACTORY_OUT_VERIFY" | grep -q "^CHECKS: no" && draft=--draft',
        '"$FACTORY_TOOLS/daily-branch" open-pr "$branch" $draft --note-file "{{run.dir}}/checks.md"',
      ].join("\n"),
    },
  ],
});
