#!/usr/bin/env node
// Builds the GitHub flows in flows/ from the blocks in blocks/, so they never drift apart.
// Usage: node scripts/build-flows.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse, stringify } from "yaml";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const block = (id) => parse(readFileSync(join(root, "blocks", `${id}.yaml`), "utf8")).steps;
const steps = (...ids) => ids.flatMap((id) => (typeof id === "string" ? block(id) : [id]));
const patch = (list, id, fields) => Object.assign(list.find((s) => s.id === id), fields);

function write(name, header, flow) {
  const text = `# ${"─".repeat(3)} ${header.title} ${"─".repeat(Math.max(3, 66 - header.title.length))}
# Generated by scripts/build-flows.mjs from blocks/*.yaml — edit the blocks or the script.
${header.lines.map((l) => `# ${l}`).join("\n")}
# ${"─".repeat(72)}
`;
  writeFileSync(join(root, "flows", `${name}.yaml`), text + stringify({ name, ...flow }, { lineWidth: 0 }));
  console.log(`wrote flows/${name}.yaml (${flow.steps.length} steps)`);
}

const ticketStart = () => {
  const s = steps("github-repo", "pull-ticket", "pull-repo", "plan", "push-plan", "code", "run-tests", "code-review");
  // After someone answers the questions, re-read the ticket and plan again.
  patch(s, "ask_for_info", { resume_from: "pull_ticket" });
  // After review changes, re-run the tests before reviewing again.
  patch(s, "address_review", { on_success: "run_tests" });
  return s;
};

// ── github-issue: ticket → pushed branch ──
write("github-issue", {
  title: "GitHub ticket → code → pushed branch",
  lines: [
    "factory run github-issue --var github_repo=owner/repo --var issue=42",
    "",
    "check repo → pull ticket → clone → plan ─┬─ unclear → ask on ticket → stop (resumes when answered)",
    "                                         └─ ready → post plan → code",
    "  → tests ⟲ fix → review ⟲ address (→ tests) → commit → push → report on ticket",
  ],
}, {
  description: "GitHub ticket → plan (or ask for info) → code → tests → review → commit, push, report",
  workspace: "empty",
  defaults: { model: "sonnet", timeout_sec: 1800 },
  limits: { max_cost_usd: 15 },
  vars: { github_repo: "owner/repo", issue: "", test_cmd: "auto" },
  steps: [...ticketStart(), ...steps("commit", "push", "push-result")],
});

// ── github-pr: ticket → PR → green CI ──
{
  const s = [
    ...ticketStart(),
    ...steps("commit"),
    {
      id: "approval_gate",
      type: "shell",
      description: "Set var require_approval=yes to ask on the ticket before pushing",
      run: 'echo "APPROVAL: ${FACTORY_VAR_REQUIRE_APPROVAL:-no}"',
      routes: [{ if: "^APPROVAL: yes", goto: "request_approval" }],
    },
    ...steps("request-approval", "push", "open-pr", "ci", "push-result", "learn"),
  ];
  patch(s, "request_approval", { jump_only: true, on_success: "approve" });
  patch(s, "approve", { jump_only: true, on_success: "push" });
  write("github-pr", {
    title: "GitHub ticket → pull request → green CI",
    lines: [
      "factory run github-pr --var github_repo=owner/repo --var issue=42 [--var require_approval=yes]",
      "",
      "like github-issue, then: [approval on ticket] → push → open PR → wait for CI ⟲ fix → report → learn",
    ],
  }, {
    description: "GitHub ticket → plan → code → tests → review → PR → CI fix loop → report → learn",
    workspace: "empty",
    defaults: { model: "sonnet", timeout_sec: 1800 },
    limits: { max_cost_usd: 20 },
    vars: { github_repo: "owner/repo", issue: "", test_cmd: "auto", require_approval: "no" },
    steps: s,
  });
}

// ── pr-feedback: address review comments on a factory PR ──
write("pr-feedback", {
  title: "Address review comments on a pull request",
  lines: ["factory run pr-feedback --var github_repo=owner/repo --var pr=17", "(the watcher runs this automatically for new comments on factory PRs)"],
}, {
  description: "Check out a PR, address its review comments, test, push, reply on the PR",
  workspace: "empty",
  defaults: { model: "sonnet", timeout_sec: 1800 },
  limits: { max_cost_usd: 10 },
  vars: { github_repo: "owner/repo", pr: "", test_cmd: "auto" },
  steps: [
    ...steps("pr-comments", "run-tests"),
    {
      id: "push_changes",
      type: "shell",
      run: [
        "git add -A",
        'git diff --cached --quiet && { echo "no code changes"; exit 0; }',
        'git commit -q -m "Address review comments" -m "Automated by claude-factory (run $FACTORY_RUN_ID)"',
        "git push -q && git log --oneline -1",
      ].join("\n"),
    },
    {
      id: "reply",
      type: "shell",
      run: [
        '{ echo "🤖 **claude-factory** went through the review comments:"; echo',
        '  printf \'%s\\n\' "$FACTORY_OUT_ADDRESS_COMMENTS"',
        '  echo; echo "<!-- claude-factory run=$FACTORY_RUN_ID -->"; } \\',
        '  | gh pr comment "$FACTORY_VAR_PR" --repo "$FACTORY_VAR_GITHUB_REPO" --body-file -',
      ].join("\n"),
    },
  ],
});
