#!/usr/bin/env node
// Builds the GitHub flows in flows/ from the blocks in blocks/, so they never drift apart.
// Usage: node scripts/build-flows.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse, stringify } from "yaml";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const block = (id) => parse(readFileSync(join(root, "blocks", `${id}.yaml`), "utf8")).steps;
const steps = (...ids) => ids.flatMap((id) => (typeof id === "string" ? block(id) : [id]));
const patch = (list, id, fields) => Object.assign(list.find((s) => s.id === id), fields);

function write(name, header, flow) {
  const text = `# ${"─".repeat(3)} ${header.title} ${"─".repeat(Math.max(3, 66 - header.title.length))}
# Generated by scripts/build-flows.mjs from blocks/*.yaml — edit the blocks or the script.
${header.lines.map((l) => `# ${l}`).join("\n")}
# ${"─".repeat(72)}
`;
  writeFileSync(join(root, "flows", `${name}.yaml`), text + stringify({ name, ...flow }, { lineWidth: 0 }));
  console.log(`wrote flows/${name}.yaml (${flow.steps.length} steps)`);
}

const ticketStart = () => {
  const s = steps("github-repo", "pull-ticket", "pull-repo", "plan", "push-plan", "code", "run-tests", "code-review");
  // After someone answers the questions, re-read the ticket and plan again.
  patch(s, "ask_for_info", { resume_from: "pull_ticket" });
  // After review changes, re-run the tests before reviewing again.
  patch(s, "address_review", { on_success: "run_tests" });
  return s;
};

// ── github-issue: ticket → pushed branch ──
write("github-issue", {
  title: "GitHub ticket → code → pushed branch",
  lines: [
    "factory run github-issue --var github_repo=owner/repo --var issue=42",
    "",
    "check repo → pull ticket → clone → plan ─┬─ unclear → ask on ticket → stop (resumes when answered)",
    "                                         └─ ready → post plan → code",
    "  → tests ⟲ fix → review ⟲ address (→ tests) → commit → push → report on ticket",
  ],
}, {
  description: "GitHub ticket → plan (or ask for info) → code → tests → review → commit, push, report",
  workspace: "empty",
  defaults: { model: "sonnet", timeout_sec: 1800 },
  limits: { max_cost_usd: 15 },
  vars: { github_repo: "owner/repo", issue: "", test_cmd: "auto" },
  steps: [...ticketStart(), ...steps("commit", "push", "push-result")],
});

// ── github-pr: ticket → PR → green CI ──
{
  const s = [
    ...ticketStart(),
    ...steps("commit"),
    {
      id: "approval_gate",
      type: "shell",
      description: "Set var require_approval=yes to ask on the ticket before pushing",
      run: 'echo "APPROVAL: ${FACTORY_VAR_REQUIRE_APPROVAL:-no}"',
      routes: [{ if: "^APPROVAL: yes", goto: "request_approval" }],
    },
    ...steps("request-approval", "push", "open-pr", "ci", "push-result", "learn"),
  ];
  patch(s, "request_approval", { jump_only: true, on_success: "approve" });
  patch(s, "approve", { jump_only: true, on_success: "push" });
  write("github-pr", {
    title: "GitHub ticket → pull request → green CI",
    lines: [
      "factory run github-pr --var github_repo=owner/repo --var issue=42 [--var require_approval=yes]",
      "",
      "like github-issue, then: [approval on ticket] → push → open PR → wait for CI ⟲ fix → report → learn",
    ],
  }, {
    description: "GitHub ticket → plan → code → tests → review → PR → CI fix loop → report → learn",
    workspace: "empty",
    defaults: { model: "sonnet", timeout_sec: 1800 },
    limits: { max_cost_usd: 20 },
    vars: { github_repo: "owner/repo", issue: "", test_cmd: "auto", require_approval: "no" },
    steps: s,
  });
}

// ── github-auto: triage decides small / feature / split / questions ──
{
  const s = [
    ...steps("github-repo", "pull-ticket", "pull-repo", "triage", "plan", "push-plan", "code", "run-tests", "code-review", "commit", "push", "open-pr", "ci", "push-result", "learn"),
  ];
  patch(s, "triage", {
    routes: [
      { if: "^ROUTE: NEEDS_INFO", goto: "ask_for_info" },
      { if: "^ROUTE: SPLIT", goto: "split_ticket" },
      { if: "^ROUTE: SMALL", goto: "implement" },
    ],
  });
  patch(s, "ask_for_info", { resume_from: "pull_ticket" });
  patch(s, "address_review", { on_success: "run_tests" });
  write("github-auto", {
    title: "GitHub ticket → triage → the right amount of process",
    lines: [
      "factory run github-auto --var github_repo=owner/repo --var issue=42",
      "",
      "triage ─┬─ SMALL      → code → tests → review → PR → CI",
      "        ├─ FEATURE    → plan → post plan → code → …",
      "        ├─ SPLIT      → create sub-issues (labelled claude-factory if auto_subtasks=yes) → end",
      "        └─ NEEDS_INFO → ask on the ticket → stop (resumes when answered)",
    ],
  }, {
    description: "Triage the ticket, then small fix, full feature, split into sub-issues, or ask questions",
    workspace: "empty",
    defaults: { model: "sonnet", timeout_sec: 1800 },
    limits: { max_cost_usd: 20 },
    vars: { github_repo: "owner/repo", issue: "", test_cmd: "auto", auto_subtasks: "no" },
    steps: s,
  });
}

// ── jira-ticket / linear-ticket: tickets elsewhere, code in the local repo ──
for (const [tool, label] of [["jira", "Jira"], ["linear", "Linear"]]) {
  const s = [
    ...steps(`${tool}-pull-ticket`, "plan"),
    ...steps(`${tool}-push-plan`, "code", "run-tests", "code-review", "commit"),
    { id: "push", type: "shell", run: 'git push -q -u origin HEAD && echo "pushed $(git branch --show-current)"' },
    ...steps(`${tool}-push-result`),
  ];
  // Without GitHub there is nowhere to ask; stop so a human can look at the questions in the run.
  patch(s, "ask_for_info", {
    run: 'printf \'%s\n\' "$FACTORY_OUT_PLAN" | sed -E \'/^(PLAN_STATUS|ROUTE):/d\'',
    on_success: "stop",
    resume_from: "pull_ticket",
    description: "Show Claude's questions and stop; answer on the ticket, then resume the run",
  });
  patch(s, "address_review", { on_success: "run_tests" });
  write(`${tool}-ticket`, {
    title: `${label} ticket → code in this repo → pushed branch`,
    lines: [
      `factory run ${tool}-ticket --var ticket=${tool === "jira" ? "PROJ-123" : "ENG-123"}   (from inside your repo)`,
      tool === "jira" ? "needs env JIRA_BASE_URL, JIRA_EMAIL, JIRA_API_TOKEN" : "needs env LINEAR_API_KEY",
    ],
  }, {
    description: `${label} ticket → plan (posted to ${label}) → code → tests → review → commit → push → result on ${label}`,
    workspace: "worktree",
    defaults: { model: "sonnet", timeout_sec: 1800 },
    limits: { max_cost_usd: 15 },
    vars: { ticket: "", test_cmd: "auto" },
    steps: s,
  });
}

// ── pr-feedback: address review comments on a factory PR ──
write("pr-feedback", {
  title: "Address review comments on a pull request",
  lines: ["factory run pr-feedback --var github_repo=owner/repo --var pr=17", "(the watcher runs this automatically for new comments on factory PRs)"],
}, {
  description: "Check out a PR, address its review comments, test, push, reply on the PR",
  workspace: "empty",
  defaults: { model: "sonnet", timeout_sec: 1800 },
  limits: { max_cost_usd: 10 },
  vars: { github_repo: "owner/repo", pr: "", test_cmd: "auto" },
  steps: [
    ...steps("pr-comments", "run-tests"),
    {
      id: "push_changes",
      type: "shell",
      run: [
        "git add -A",
        'git diff --cached --quiet && { echo "no code changes"; exit 0; }',
        'git commit -q -m "Address review comments" -m "Automated by claude-factory (run $FACTORY_RUN_ID)"',
        "git push -q && git log --oneline -1",
      ].join("\n"),
    },
    {
      id: "reply",
      type: "shell",
      run: [
        '{ echo "🤖 **claude-factory** went through the review comments:"; echo',
        '  printf \'%s\\n\' "$FACTORY_OUT_ADDRESS_COMMENTS"',
        '  echo; echo "<!-- claude-factory run=$FACTORY_RUN_ID -->"; } \\',
        '  | gh pr comment "$FACTORY_VAR_PR" --repo "$FACTORY_VAR_GITHUB_REPO" --body-file -',
      ].join("\n"),
    },
  ],
});

// ── ci-fix: CI failing on the default branch → fix PR ──
{
  const s = [
    ...steps("github-repo", "pull-repo"),
    {
      id: "ci_logs",
      type: "shell",
      description: "Failed job logs of CI run ci_run (set by the ci-failures watcher)",
      run: [
        'case "$FACTORY_VAR_CI_RUN" in *[!0-9]*|"") echo "set var ci_run to a GitHub Actions run id"; exit 1;; esac',
        'gh run view "$FACTORY_VAR_CI_RUN" --repo "$FACTORY_VAR_GITHUB_REPO" --json workflowName,headSha,headBranch,url \\',
        '  --jq \'"workflow: \\(.workflowName)\\ncommit: \\(.headSha)\\nbranch: \\(.headBranch)\\nurl: \\(.url)"\'',
        'echo; echo "=== failed job logs (tail) ==="',
        'gh run view "$FACTORY_VAR_CI_RUN" --repo "$FACTORY_VAR_GITHUB_REPO" --log-failed 2>&1 | tail -200',
      ].join("\n"),
    },
    {
      id: "implement",
      type: "claude",
      permission_mode: "acceptEdits",
      allowed_tools: ["Read", "Edit", "Write", "Glob", "Grep", "Bash(npm *)", "Bash(npx *)", "Bash(git log*)", "Bash(git diff*)", "Bash(git show*)"],
      prompt: [
        "CI is failing on the default branch. Find the root cause and fix it with the smallest",
        "correct change. Do not disable, skip or loosen tests or checks. Use `git log` to see which",
        "recent commits could have caused it.",
        "",
        "{{steps.ci_logs.output}}",
        "",
        "Things learned from earlier runs in this repo:",
        "{{learnings}}",
        "",
        "Finish with a short summary of the cause and the fix.",
      ].join("\n"),
    },
    ...steps("run-tests", "code-review", "commit", "push", "open-pr", "ci", "learn"),
  ];
  patch(s, "address_review", { on_success: "run_tests" });
  write("ci-fix", {
    title: "CI failing on the default branch → fix pull request",
    lines: [
      "factory run ci-fix --var github_repo=owner/repo --var ci_run=123456789",
      "(the ci-failures watcher runs this when the latest run of a workflow on the default branch failed)",
      "",
      "clone → failed logs → fix → tests ⟲ fix → review ⟲ address → commit → push → PR → CI ⟲ fix → learn",
    ],
  }, {
    description: "Fix CI that is red on the default branch: read the failed logs, fix, test, review, open a PR",
    workspace: "empty",
    defaults: { model: "sonnet", timeout_sec: 1800 },
    limits: { max_cost_usd: 15 },
    vars: { github_repo: "owner/repo", ci_run: "", test_cmd: "auto" },
    steps: s,
  });
}

// ── chore: recurring maintenance on a schedule → PR (or nothing) ──
{
  const s = [
    ...steps("github-repo", "pull-repo"),
    {
      id: "implement",
      type: "claude",
      permission_mode: "acceptEdits",
      allowed_tools: ["Read", "Edit", "Write", "Glob", "Grep", "Bash(npm *)", "Bash(npx *)", "Bash(pnpm *)", "Bash(yarn *)", "Bash(git log*)", "Bash(git diff*)"],
      prompt: [
        "Recurring maintenance task for this repository:",
        "",
        "{{task}}",
        "",
        "Keep the change focused and safe to merge. If nothing needs to be done, change nothing",
        "and answer with exactly: NOTHING_TO_DO",
        "Otherwise finish with a short summary of what you changed and why.",
      ].join("\n"),
      routes: [{ if: "^NOTHING_TO_DO\\s*$", goto: "end" }],
    },
    ...steps("run-tests", "code-review", "commit", "push", "open-pr", "ci"),
  ];
  patch(s, "address_review", { on_success: "run_tests" });
  write("chore", {
    title: "Scheduled chore → pull request (or nothing to do)",
    lines: [
      'factory run chore --var github_repo=owner/repo "Update dependencies with known vulnerabilities"',
      "(a schedule watcher runs this on a timer with its task)",
      "",
      "clone → do the chore ─┬─ nothing to do → end",
      "                      └─ changed → tests ⟲ fix → review → commit → push → PR → CI ⟲ fix",
    ],
  }, {
    description: "Recurring maintenance (deps, flaky tests, docs…) on a schedule; opens a PR only if something changed",
    workspace: "empty",
    defaults: { model: "sonnet", timeout_sec: 1800 },
    limits: { max_cost_usd: 10 },
    vars: { github_repo: "owner/repo", test_cmd: "auto" },
    steps: s,
  });
}
